clc;
clear all;
close all;
A=4.5;
f=2; 
Q=0;
t = 0:0.01:7; 
sin = A*sin(2*pi*f*t+Q);
cos= A*cos(2*pi*f*t+Q);
figure;
subplot(2,1,1);
plot(t, sin, 'g', 'linewidth', 1.5);
title('Sine Wave');
xlabel('Time');
ylabel('Amplitude');
grid off;
subplot(2,1,2);
plot(t, cos, 'r', 'linewidth', 1.5);
title('Cosine Wave');
xlabel('Time');
ylabel('Amplitude');